### ISSUE TITLE
I have working graphics accelration of this laptop

### ISSUE THREAD

**Issue by muhamadahmadbzu** [rowell1/GPD-P2-Max-2019-Hackintosh#1]
hey, wanted to let you know I have working graphics acceleration of this laptop which is m3 8100Y. if you want the EFI do let me know I will happily upload it here.

**Comment by rowell1** [comment]
Yes please, I was hoping there were still Hackintosh enthusiasts left for a 4 year old GPD P2 Max 2019.
My current repo is now an multi-bootpicker for the latest Sonoma 14.3.1 (Ventura, Monterey, BigSur) and Windows 10.

**Comment by rowell1** [comment]
@muhamadahmadbzu
Yes please. (Sorry for accidentally closing/reopening your comment.)

**Comment by muhamadahmadbzu** [comment]
[Config.plist.zip](https://github.com/rowell1/GPD-P2-Max-2019-Hackintosh/files/14319270/Config.plist.zip)

here, you can inject your own LCD EDID to get proper resolution, after that you will have proper acceleration of intel UHD 615 :)
